spring:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      show-sql: 'false'
      ddl-auto: none
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            credential.managed-identity-enabled: true
            endpoint: "https://demoazure.vault.azure.net/"