spring:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      show-sql: 'false'
      ddl-auto: none

#  cloud:
#    azure:
#      keyvault:
#        secret:
#          property-sources[0]:
#            credential:
#              client-id: "c8dc3c12-f485-475d-8aab-d27b941ea1a2"
#            endpoint: "https://demoazure.vault.azure.net/"